language: go
sudo: required
dist: trusty

go:
  - 1.12

services:
- docker

before_install:
  - sudo apt-get update 
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install docker-ce
  - sudo apt-get install golang -y
  - docker version

install:
- sudo apt-get install dnsmasq python -y
- sudo pip install botocore
- sudo sed -i "$ a\address=/.s3.test.com/10.5.0.18" /etc/dnsmasq.conf
- sudo sed -i "$ a\address=/.s3-internal.test.com/10.5.0.18" /etc/dnsmasq.conf
- sudo service dnsmasq restart
- sudo sed -i "1 i\nameserver 127.0.0.1" /etc/resolv.conf
- sudo ufw disable

script:
- make integrate
- export GO111MODULE=on
- sudo python test/sanity.py
- pushd test/go
- go test -v
- popd
- cat lc.log

before_deploy:
  - echo "prepare package"
  - sudo make pkg
  - sudo make image

deploy:
  - provider: releases
    api_key: $GithubToken
    file: $TRAVIS_BUILD_DIR/yig*.x86_64.rpm
    file_glob: true 
    skip_cleanup: true
    on:
      repo: journeymidnight/yig
      tags: true

  - provider: script
    script: echo "$DOCKER_PASSWORD"|docker login -u "$DOCKER_USERNAME" --password-stdin  && docker tag journeymidnight/yig journeymidnight/yig:$TRAVIS_TAG && docker push journeymidnight/yig:$TRAVIS_TAG
    on:
      repo: journeymidnight/yig
      tags: true

  - provider: script
    script: echo "$DOCKER_PASSWORD"|docker login -u "$DOCKER_USERNAME" --password-stdin  && docker push journeymidnight/yig
    on:
      repo: journeymidnight/yig
      branch: master
