s3domain = ["s3.test.com", "s3-internal.test.com"]
region = "cn-bj-1"
log_path = "/var/log/yig/yig.log"
access_log_path = "/var/log/yig/access.log"
access_log_format = "{combined}"
panic_log_path = "/var/log/yig/panic.log"
log_level = "info"
pid_file = "/var/run/yig/yig.pid"
api_listener = "0.0.0.0:8080"
admin_listener = "0.0.0.0:9000"
admin_key = "secret"
ssl_key_path = ""
ssl_cert_path = ""
piggyback_update_usage = true

debug_mode = true
enable_pprof = false
pprof_listener = "0.0.0.0:8730"
reserved_origins = "s3.test.com,s3-internal.test.com"

# Meta Config
meta_cache_type = 2
meta_store = "tidb"
tidb_info = "root:@tcp(10.5.0.17:4000)/yig"
keepalive = true
enable_usage_push = false
redis_address = "redis:6379"
redis_password = "hehehehe"
redis_connection_number = 10
memory_cache_max_entry_count = 100000
enable_data_cache = true
redis_connect_timeout = 1
redis_read_timeout = 1
redis_write_timeout = 1
redis_keepalive = 60
redis_pool_max_idle = 3
redis_pool_idle_timeout = 30

cache_circuit_check_interval = 3
cache_circuit_close_sleep_window = 1
cache_circuit_close_required_count = 3
cache_circuit_open_threshold = 1
cache_circuit_exec_timeout = 5
cache_circuit_exec_max_concurrent = -1

db_max_open_conns = 10240
db_max_idle_conns = 1024
db_conn_max_life_seconds = 300

download_buf_pool_size = 8388608 #8MB
upload_min_chunk_size = 524288 #512KB
upload_max_chunk_size = 8388608 #8MB

# Ceph Config
ceph_config_pattern = "/etc/ceph/*.conf"

[kms]
type = "vault"
endpoint = "http://10.5.0.19:8200"
kms_id = "your_id"
kms_secret = "your_secret"
version = 0
keyname = "yig"

# Plugin Config
[plugins.kafka]
path = "/etc/yig/plugins/kafka_plugin.so"
enable = true
[plugins.kafka.args]
topic = "testTopic2"
request_timeout_ms = "3000"
message_timeout_ms = "5000"
send_max_retries = "2"
broker_list = "kafka:29092"

[plugins.dummy_iam]
path = "/etc/yig/plugins/dummy_iam_plugin.so"
enable = true
[plugins.dummy_iam.args]
url="s3.test.com"

[plugins.not_exist]
path = "not_exist_so"
enable = false
