s3domain = "s3.test.com"
s3domain_internal = "s3-internal.test.com"
region = "cn-bj-1"
log_path = "/var/log/yig/yig.log"
panic_log_path = "/var/log/yig/panic.log"
log_level = 20
pid_file = "/var/run/yig/yig.pid"
api_listener = "0.0.0.0:8080"
admin_listener = "0.0.0.0:9000"
admin_key = "secret"
ssl_key_path = ""
ssl_cert_path = ""

# DebugMode
debug_mode = true

# IAM Config
iam_endpoint = "http://10.11.144.11:9006"
iam_key = "key"
iam_secret = "secret"

# Meta Config
meta_cache_type = 2
meta_store = "tidb"
tidb_info = "root:@tcp(10.5.0.17:4000)/yig"
keepalive = true
zk_address = "hbase:2181"
redis_address = "redis:6379"
redis_connection_number = 10
memory_cache_max_entry_count = 100000
enable_data_cache = true

# Ceph Config
ceph_config_pattern = "/etc/ceph/*.conf"

[kms]
type = "vault"
endpoint = "http://10.5.0.19:8200"
id = "f7b8ae6f-5008-ceec-6a50-2497f429c8dc"
secret = "a22f513f-e4eb-d327-2566-77c92e0b4cdd"
version = 0
keyname = "yig"
